STATUS_PENDING = 'pending'
STATUS_IN_PROGRESS = 'in_progress'
STATUS_DONE = 'done'
STATUS_CANCELLED = 'cancelled'
VALID_STATUSES = (STATUS_PENDING, STATUS_IN_PROGRESS, STATUS_DONE, STATUS_CANCELLED)
# Status em que uma task não pode mais ficar atrasada.
FINAL_STATUSES = (STATUS_DONE, STATUS_CANCELLED)

ROLE_USER = 'user'
ROLE_ADMIN = 'admin'
ROLE_MANAGER = 'manager'
VALID_ROLES = (ROLE_USER, ROLE_ADMIN, ROLE_MANAGER)
PRIVILEGED_ROLES = (ROLE_ADMIN, ROLE_MANAGER)

MIN_PRIORITY = 1
MAX_PRIORITY = 5
DEFAULT_PRIORITY = 3
# Prioridade <= este valor conta como "alta" nos relatórios.
HIGH_PRIORITY_THRESHOLD = 2
PRIORITY_LABELS = {1: 'critical', 2: 'high', 3: 'medium', 4: 'low', 5: 'minimal'}

MIN_TITLE_LENGTH = 3
MAX_TITLE_LENGTH = 200
MIN_PASSWORD_LENGTH = 4
DEFAULT_COLOR = '#000000'
DATE_FORMAT = '%Y-%m-%d'
RECENT_ACTIVITY_DAYS = 7
